### ISSUE TITLE
Regarding the source-only pretrained model.

### ISSUE THREAD

**Issue by dlsrbgg33** [saltoricristiano/gipso-sfouda#2]
Dear author,

Thank you for the great work and contribution with this repository.

I am wondering how you get the source-only model. 
Did you pick the source-validation best model or last epoch model?

Thank you in advance.

**Comment by saltoricristiano** [comment]
Hi @dlsrbgg33,

thanks for the interest in our work!
We took the last epoch model. I don't remember now but the IoU should be not far from the best model.

Hope I solved your issue!

Cheers, 
Cristiano Saltori
