### ISSUE TITLE
Implementations of Baseline Models

### ISSUE THREAD

**Issue by ldkong1205** [saltoricristiano/gipso-sfouda#3]
Hi @saltoricristiano, thanks for open-sourcing this work. Your SF-OUDA setting is practical and important in terms of deployment.

I have the following two questions:
- I noticed from the paper that you have implemented a wide range of SF-UDA and Online-UDA methods. The scores of ProDA* and SHOT* in Table 2 and Table 3 are almost zeros. As you explained in Section 5.3, this might be caused by sequence length. I would like to know whether it is still reasonable to compare ProDA* and SHOT* in this way on SemanticKITTI? How about shorter the sequence length? Do you have any recent thoughts on this phenomenon?
- The second question is about implementations. Regarding these baseline models, could you share the code for implementing them? Thanks.

**Comment by saltoricristiano** [comment]
Hi @ldkong1205, 

thanks for the interest in our work!
In order:

1. Yes, centroid-based baselines seem to underperform on long sequences. For example, ProDA* and SHOT* perform similarly to Source on the short sequences of nuScenes while drop on the long sequence of SemanticKITTI. We provide also a study on the feature compactness of centroid-based methods in Fig.5b and Sec. 5.4 by using the DB Index. We didn't try to shorten the sequence of SemanticKITTI.
2. Honestly, I'm not planning to release the code of the baselines in short time as I don't have the time to clean and release it. However, baselines are quite simple to be re-implemented, we report implementation details in Sec. 5.2. If needed I can provide support for re-implementing them.

Best regards, 
@saltoricristiano

**Comment by ldkong1205** [comment]
Hi @saltoricristiano, thanks for your reply and suggestions
