### ISSUE TITLE
Uncertainty of results

### ISSUE THREAD

**Issue by tpzou** [saltoricristiano/gipso-sfouda#4]
Hi, @saltoricristiano ， Thank you open source for such great work. 

I tried to reproduce the results reported in the article, but found that the random seed don't seem to be fixed very well resulting in different results for each run. I did a simple test using `--split_size 100` in the run command, is there something I did wrong?

**Comment by saltoricristiano** [comment]
Hi @tpzou,

thanks for the interest in our project! Setting split_size to 100 will split the evaluation sequence in sequence_length/split_size sub-sequences and apply GIPSO on each sub-sequence independently. This will give you different results. We did not play with sequence lengths as it was out of our focus.

Hope I solved your doubts!
In case feel free to close this issue!
@saltoricristiano

**Comment by tpzou** [comment]
@saltoricristiano , Thank you for your reply. But my focus is not on split_size. I mean the training random seeds of the network don't seem to be fixed. When I re-run the code, I get a different result than the previous one. 

I just set split_size to 100 to speed up my validation. Theoretically, the results should be the same for the first 100 frames of each training run for the KITTI 08 sequence. However, the results show that there seems to be a big fluctuation.

**Comment by saltoricristiano** [comment]
I guess the fluctuations you are getting are due to split_size 100. As said, split_size sets the length of the evaluation sequence. If you split the sequence in sub-sequences of 100 frames, you will run GIPSO only on 100 frames and reset it after each sub-sequence adaptation. GIPSO is reset each time, therefore adaptation results will be different.

**Comment by tpzou** [comment]
Forgive me if my questions may be a little silly, but from the code, it appears that split_size 100 will only select and train the first 100 of KITTI 08.  Shouldn't the result be the same? I tried the complete 4071 sequence and the results also differed.

**Comment by saltoricristiano** [comment]
No, you will achieve the same results only with the full split_size (4071 for semantickitti). Otherwise you will split the sequence and use each sub sequence as a separate validation sequence.
However, before pushing, I run the code and have achieved similar results to the ones reported.
Which results are you getting?

**Comment by tpzou** [comment]
When I run **adapt_online.py** of kitti with split_size 100, the program runs only on the first 100. Since the data is the same for each training, I can't understand why there is a difference in performance. Here I'm referring to the results of the previous training and the next training, not 100 compared to 4071.. I think is it caused by the **random seeds** not being fixed?

The first time I got the result on complete data of synth4d2kitti it was `0,3.7853088127738688,12.822022129664878,-1.0873802401754618,1.0615092761036449,2.078065702059795,2.266526845866901,4.690222773943309,4.66619520195406
`, 
the second time it was `0,3.899122679679051,13.023207334396714,-1.510060289688031,1.0351549248591219,2.0943818141944015,2.309121180714735,4.980756569315748,5.361297223960698
`. 
Although they are similar, there is a discrepancy.

**Comment by saltoricristiano** [comment]
Ok now I got it! I apologise, I thought you were comparing 100 VS 4071.
Yes, you can try to fix the seed or to average the results of N runs. I don't know if hard coding the seed will be enough as there are other actors involved such as voxelizations and approximations.
